# Generated by Django 6.1 on 2026-08-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsite', '0002_remove_userinfo_password_remove_userinfo_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='gram_panchayat_name_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
